version: '3'

services:
  tng-vnv-planner-postgres:
    image: ntboes/postgres-uuid
    container_name: son-postgres
    environment:
      - POSTGRES_DB=planner
      - POSTGRES_USER=sonatatest
      - POSTGRES_PASSWORD=sonata
    ports:
      - '5432:5432'
    volumes:
      - tng-vnv-planner-data:/var/lib/postgresql/data

  tng-vnv-planner:
    build: ./build
    image: registry.sonata-nfv.eu:5000/tng-vnv-planner
    container_name: tng-vnv-planner
    depends_on:
      - tng-vnv-planner-postgres
    ports:
      - 6100:6100
volumes:
  tng-vnv-planner-data:

